accounts/urls.py
from django.urls import path
from .import views
# from django.contrib.auth import views as auth_views

app_name ='accounts'
urlpatterns = [
    path('signup/',views.signup,name='signup'),  
    path('profile/',views.profile,name='profile'),
    path('profile/edit',views.profile_edit,name='profile_edit'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', views.login_view, name='login'),

]

blog/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('',views.blog,name='blog'), 
    path('read_more1',views.readMore1,name='read_more1'), 
    path('read_more2',views.readMore2,name='read_more2'),
    path('read_more3',views.readMore3,name='read_more3'),
    path('read_more4',views.readMore4,name='read_more4'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about', include('about.urls')),
    path('blog', include('blog.urls')),
    path('contact', include('contact.urls')),
    path('shop', include('shop.urls')),   
    path('search', include('search.urls')),
    # path('payments/', include('payments.urls')),
    
    path('login/', auth_views.LoginView.as_view(), name='login'),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


templates/base.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Safarnee</title>
    {% comment %} {% bootstrap_css %}
    {% bootstrap_javascript %} {% endcomment %}
    <!-- Render All Elements Normally -->
    <link rel="stylesheet" href="{% static 'CSS/normalize.css' %}" />
    <!-- Font Awesome Library -->
    <link href="{% static 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"rel="stylesheet' %}"/>
    <link rel="stylesheet" href="{% static 'CSS/all.min.css' %}" />
    <!-- Main Template CSS File -->
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}" />

    <link rel="stylesheet" href="{% static 'CSS/login.css' %}">

    <!-- Google Fonts -->
    <link rel="preconnect" href="{% static 'https://fonts.googleapis.com' %}" />
    <link
      rel="preconnect"
      href="{% static 'https://fonts.gstatic.com' %}"
      crossorigin
    />
    <link
      href="{% static 'https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;700&#038;display=swap' %}"
      rel="stylesheet"
    />
    <style>

    </style>
    {% comment %} <link rel="stylesheet" href="{% static 'CSS/search.css' %}" /> {% endcomment %}
    {% block add %}{% endblock add %}
  </head>
  <body>
    <!-- Start Header  -->
    <header id="header">
      <div class="container">
        <a href="{% url 'home' %}" class="logo" title="Safarnee">Safarnee</a>
        <nav>
          <i
            class="fas fa-bars toggle-menu"
            onClick="showBar()"
            id="toggle-menu-btn"
          ></i>
          <ul class="main-nav">
            <li>
                <a href="{% url 'home' %}" class="{% if request.path == '/' %}active{% endif %}">Home</a>
            </li>
            <li>
                <a href="{% url 'shop' %}" class="{% if 'shop' in request.path %}active{% endif %}">Shop</a>
            </li>
            <li>
                <a href="{% url 'blog' %}" class="{% if 'blog' in request.path %}active{% endif %}">Blog</a>
            </li>
            <li>
                <a href="{% url 'about' %}" class="{% if 'about' in request.path %}active{% endif %}">About</a>
            </li>
            <li>
                <a href="{% url 'contact' %}" class="{% if 'contact' in request.path %}active{% endif %}">Contact</a>
            </li>
            <li>
                <a href="{% url 'search' %}" class="{% if 'search' in request.path %}active{% endif %}">Hotels</a>
            </li>
        </ul>
        
        
        
        
          
        {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:profile' %}">
              <button class="btn btn-login">
                Profile<i class="fa-regular fa-user"></i>
              </button>
            </a>
            {% if profile and profile.image %}
              <img src="{{ profile.image.url }}" alt="Profile Photo" style="width: 40px; height: 40px; border-radius: 50%; object-fit: cover; margin-left: 10px;">
            {% endif %}
            <form action="{% url 'logout' %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn btn-login">
                Logout <i class="fas fa-arrow-alt-circle-right"></i>
              </button>
            </form>
          {% else %}
            <a href="{% url 'login' %}">
              <button class="btn btn-login">
                Login<i class="fa-regular fa-user"></i>
              </button>
            </a>
            <a href="{% url 'accounts:signup' %}">
              <button class="btn btn-login">
                Signup<i class="fa-regular fa-user"></i>
              </button>
            </a>
          {% endif %}

         
          
          <img
            src="{% static 'images/palstineFlag.png' %}"
            alt="free palestine"
            title="#Free Palestine"
          />
        </nav>
        <!-- Login form -->
        {% comment %} <div class="login-form">
          <form action="">
            <i class="fas fa-times" id="form-close" onclick="hideForm()"></i>
            <h2 class="title">login</h2>
            <input
              type="email"
              class="box"
              placeholder="Enter your email"
              required
            />
            <input
              type="password"
              class="box"
              placeholder="Enter your password"
              autocomplete="cc-number"
              required
            />
            <!-- autocomplete="cc-csc" -->
            <input type="submit" class="box btn" value="login now" />
            <label for="remm">remember me.</label>
            <input type="checkbox" id="remm" class="rem" />
            <p>forget password? <a href="">click here..</a></p>
            <p>
              don't have acount?
              <a href="#register" onclick="showFormRegister()">Sign Up</a>
            </p>
          </form>
        </div> {% endcomment %}
        
        
      </div>
    </header>
    <!-- End Header  -->

{% block content %}

{% endblock content %}

    <!-- Start Footer -->
    <footer>
      <div class="container-footer">
        <div class="row box">
          <div class="col" id="company">
            <a href="{% url "home" %}" class="logo footer" title="Safarnee"
              >Safarnee</a
            >
            <p>Travel beyond your imagination, with our Travel Agency!</p>
            <div class="social">
              <a
                href="https://www.facebook.com"
                title="facebook"
                style="--clr: #1877f2"
                ><i class="fab fa-facebook"></i
              ></a>
              <a
                href="https://www.instagram.com"
                title="instagram"
                style="--clr: #c32aa3"
                ><i class="fab fa-instagram"></i
              ></a>
              <a
                href="https://www.youtube.com"
                title="youtube"
                style="--clr: #f00"
                ><i class="fab fa-youtube"></i
              ></a>
              <a
                href="https://www.twitter.com"
                title="x-twitter"
                style="--clr: #e7e9ea"
                ><i class="fa-brands fa-x-twitter"></i
              ></a>
              <a
                href="https://www.linkedin.com"
                title="linkedin"
                style="--clr: #114a66"
                ><i class="fab fa-linkedin"></i
              ></a>
            </div>
          </div>

          <div class="col" id="services">
            <h3>Services</h3>
            <div class="links">
              <a href="#travel">Travel</a>
              <a href="#">Outside Tourism</a>
              <a href="#">Trips</a>
              <a href="#">Domestic Tourism</a>
            </div>
          </div>

          <div class="col" id="useful-links">
            <h3>Links</h3>
            <div class="links">
              <a href="{% url 'shop' %}">Shop</a>
              <a href="{% url 'blog' %}">Blog</a>
              <a href="{% url 'about' %}">About Us</a>
              <a href="{% url 'contact' %}">Contact Us</a>
            </div>
          </div>

          <div class="col" id="contact">
            <h3>Contact</h3>
            <div class="contact-details">
              <i class="fa fa-location"></i>
              <p>Rafah - Gaza</p>
            </div>
            <div class="contact-details">
              <i class="fa fa-phone"></i>
              <p>+970 599 000 000</p>
            </div>
            <div class="contact-details">
              <i class="fa fa-envelope"></i>
              <p>Safarnee@gmail.com</p>
            </div>
          </div>
        </div>
        <p class="rights">© 2024 Safarnee. All Rights Reserved.</p>
      </div>
    </footer>
    <!-- End Footer -->
  </body>
</html>

templates/base2.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Safarnee</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <!-- Render All Elements Normally -->
    <link rel="stylesheet" href="{% static 'CSS/normalize.css' %}" />
    <!-- Font Awesome Library -->
    <link href="{% static 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"rel="stylesheet' %}"/>
    <link rel="stylesheet" href="{% static 'CSS/all.min.css' %}" />
    <!-- Main Template CSS File -->
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}" />

    <link rel="stylesheet" href="{% static 'CSS/login.css' %}">

    <!-- Google Fonts -->
    <link rel="preconnect" href="{% static 'https://fonts.googleapis.com' %}" />
    <link
      rel="preconnect"
      href="{% static 'https://fonts.gstatic.com' %}"
      crossorigin
    />
    <link
      href="{% static 'https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;700&#038;display=swap' %}"
      rel="stylesheet"
    />
    <style>
        header nav img {
            width: 40px;
            margin-left: 10px;
            -webkit-transition: var(--main-transition);
            -moz-transition: var(--main-transition);
            -ms-transition: var(--main-transition);
            -o-transition: var(--main-transition);
            transition: var(--main-transition);
        }
    </style>
    {% comment %} <link rel="stylesheet" href="{% static 'CSS/search.css' %}" /> {% endcomment %}
    {% block add %}{% endblock add %}
  </head>
  <body>
    <!-- Start Header  -->
    <header id="header">
      <div class="container">
        <a href="{% url 'home' %}" class="logo" title="Safarnee">Safarnee</a>
        <nav>
          <i
            class="fas fa-bars toggle-menu"
            onClick="showBar()"
            id="toggle-menu-btn"
          ></i>
          <ul class="main-nav">
            <li>
              <a href="{% url 'home' %}" class="{% if request.path == '/' %}active{% endif %}">Home</a>
            </li>
            <li>
              <a href="{% url 'shop' %}" class="{% if request.path == '/shop/' %}active{% endif %}">Shop</a>
            </li>
            <li>
              <a href="{% url 'blog' %}" class="{% if request.path == '/blog/' %}active{% endif %}">Blog</a>
            </li>
            <li>
              <a href="{% url 'about' %}" class="{% if request.path == '/about/' %}active{% endif %}">About</a>
            </li>
            <li>
              <a href="{% url 'contact' %}" class="{% if request.path == '/contact/' %}active{% endif %}">Contact</a>
            </li>
            <li>
              <a href="{% url 'search' %}" class="{% if request.path == '/search/' %}active{% endif %}">Hotels</a>
            </li>
          </ul>
          
        {% if request.user.is_authenticated %}
          <a href="{% url 'accounts:profile' %}">
            <button class="btn btn-login">
              Profile<i class="fa-regular fa-user"></i>
            </button>
          </a>
          <form action="{% url 'logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-login">
              Logout <i class="fas fa-arrow-alt-circle-right"></i>
            </button>
          </form>
          
        
        
        {% else %}
          <a href="{% url 'login' %}">
            <button class="btn btn-login">
              Login<i class="fa-regular fa-user"></i>
            </button>
          </a>
          <a href="{% url 'accounts:signup' %}">
            <button class="btn btn-login">
              Signup<i class="fa-regular fa-user"></i>
            </button>
          </a>
        {% endif %}

         
          
          <img
            src="{% static 'images/palstineFlag.png' %}"
            alt="free palestine"
            title="#Free Palestine"
            style="width: 40px; height: auto; margin-left: 10px; transition: var(--main-transition);"

          />
        </nav>
        <!-- Login form -->
        {% comment %} <div class="login-form">
          <form action="">
            <i class="fas fa-times" id="form-close" onclick="hideForm()"></i>
            <h2 class="title">login</h2>
            <input
              type="email"
              class="box"
              placeholder="Enter your email"
              required
            />
            <input
              type="password"
              class="box"
              placeholder="Enter your password"
              autocomplete="cc-number"
              required
            />
            <!-- autocomplete="cc-csc" -->
            <input type="submit" class="box btn" value="login now" />
            <label for="remm">remember me.</label>
            <input type="checkbox" id="remm" class="rem" />
            <p>forget password? <a href="">click here..</a></p>
            <p>
              don't have acount?
              <a href="#register" onclick="showFormRegister()">Sign Up</a>
            </p>
          </form>
        </div> {% endcomment %}
        
        
      </div>
    </header>
    <!-- End Header  -->

{% block blog %}

{% endblock  %}

    <!-- Start Footer -->
    <footer>
      <div class="container-footer">
        <div class="row box">
          <div class="col" id="company">
            <a href="{% url "home" %}" class="logo footer" title="Safarnee"
              >Safarnee</a
            >
            <p>Travel beyond your imagination, with our Travel Agency!</p>
            <div class="social">
              <a
                href="https://www.facebook.com"
                title="facebook"
                style="--clr: #1877f2"
                ><i class="fab fa-facebook"></i
              ></a>
              <a
                href="https://www.instagram.com"
                title="instagram"
                style="--clr: #c32aa3"
                ><i class="fab fa-instagram"></i
              ></a>
              <a
                href="https://www.youtube.com"
                title="youtube"
                style="--clr: #f00"
                ><i class="fab fa-youtube"></i
              ></a>
              <a
                href="https://www.twitter.com"
                title="x-twitter"
                style="--clr: #e7e9ea"
                ><i class="fa-brands fa-x-twitter"></i
              ></a>
              <a
                href="https://www.linkedin.com"
                title="linkedin"
                style="--clr: #114a66"
                ><i class="fab fa-linkedin"></i
              ></a>
            </div>
          </div>

          <div class="col" id="services">
            <h3>Services</h3>
            <div class="links">
              <a href="#travel">Travel</a>
              <a href="#">Outside Tourism</a>
              <a href="#">Trips</a>
              <a href="#">Domestic Tourism</a>
            </div>
          </div>

          <div class="col" id="useful-links">
            <h3>Links</h3>
            <div class="links">
              <a href="{% url 'shop' %}">Shop</a>
              <a href="{% url 'blog' %}">Blog</a>
              <a href="{% url 'about' %}">About Us</a>
              <a href="{% url 'contact' %}">Contact Us</a>
            </div>
          </div>

          <div class="col" id="contact">
            <h3>Contact</h3>
            <div class="contact-details">
              <i class="fa fa-location"></i>
              <p>Shebeen - Menoufia - Egypt</p>
            </div>
            <div class="contact-details">
              <i class="fa fa-phone"></i>
              <p>+20 1069641013</p>
            </div>
            <div class="contact-details">
              <i class="fa-solid fa-envelope fa-xs"></i>
              <p>safarnee@gmail.com</p>
            </div>
          </div>
        </div>

        <!-- <div class="row">
          <div class="form-con">
            <form action="">
              <input type="email" placeholder="Email here..." required />
              <button class="btn" title="Send">
                <i class="fa fa-paper-plane"></i>
              </button>
            </form>
          </div>
        </div>
      </div>
      <div class="flag-clr"></div>
      <div class="flag"></div> -->
    </footer>
    <!-- End footer -->

    <!-- Arrow Go To Up Website  -->
    <button class="scrollUp" title="Up">
      <i class="fa-solid fa-angles-up fa-l"></i>
    </button>

    <!--*  Java Script  *-->
    <script src="{% static 'main.js' %}"></script>
    <script src="{% static './js/details.js' %}"></script> 
    <script src="{% static './js/search.js' %}"></script>
    <script src="{% static 'https://js.stripe.com/v3/' %}"></script>
    <script src="{% static './js/cultural-tourism.js' %}"></script> 
    <script src="{% static './js/eco-tourism.js' %}"></script>
    <script src="{% static './js/leisure-tourism.js' %}"></script>   
    <script src="{% static './js/religious-tourism.js' %}"></script>



   
    
  </body>
</html>

templates/base_generic.html
{% extends 'base2.html' %}


{% block blog %} 
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        {% block body %}
                        {% endblock body %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock  %}